Add onInitialStateReceived callback, update Kotlin to 2.0
Kontur-Mobile/VisualFSM pull request #33
Opened 2024-10-26 08:29 UTC by VasilyRylov

2024-10-28 13:17 UTC, g0rd1 requested changes

2024-10-28 13:17 UTC, g0rd1 commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/transitioncallbacks/LogTransitionCallbacks.kt
> +class LogTransitionCallbacks<STATE : State>(
Похоже не дописана реализация

2024-10-28 13:17 UTC, g0rd1 commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/transitioncallbacks/StdoutFSMLogger.kt
> +    override fun e(message: String, exception: Exception, errorGroupId: String) {
А точно мы хотим целых 4 сообщения выдавать? Ещё и message 2 раза выводим

2024-10-28 13:17 UTC, g0rd1 commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/transitioncallbacks/TransitionCallbacksAggregator.kt
> +class TransitionCallbacksAggregator<STATE : State>(
Не используется. Точно хотим оставить? Как будто пользователи сами в состоянии в случае необходимости написать агрегатор или декоратор

2024-10-28 13:17 UTC, g0rd1 commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/TransitionCallbacks.kt
>      fun onMultipleTransitionError(
Обсуждали с тобой, что в этот колбэк метод было бы неплохо передать все подошедшие транзишены для отладки

2024-10-28 13:17 UTC, g0rd1 commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/TransitionCallbacks.kt
>  interface TransitionCallbacks<STATE : State> {
И вот здесь если накинуть ACTION в дженерик параметры, то в реализациях можно будет when по экшену без каста делать

2025-04-01 08:23 UTC, VasilyRylov commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/transitioncallbacks/LogTransitionCallbacks.kt
> +class LogTransitionCallbacks<STATE : State>(
Была не дописана в концепте

2025-04-01 08:24 UTC, VasilyRylov commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/transitioncallbacks/StdoutFSMLogger.kt
> +    override fun e(message: String, exception: Exception, errorGroupId: String) {
Коммент похоже устарел

2025-04-01 08:25 UTC, VasilyRylov commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/transitioncallbacks/TransitionCallbacksAggregator.kt
> +class TransitionCallbacksAggregator<STATE : State>(
Не использовался в концепте

2025-04-01 08:26 UTC, VasilyRylov commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/TransitionCallbacks.kt
>      fun onMultipleTransitionError(
Добавил suitableTransitions List

2025-04-01 08:26 UTC, VasilyRylov commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/TransitionCallbacks.kt
>  interface TransitionCallbacks<STATE : State> {
ACTION в дженерик добавлен

2025-04-02 06:45 UTC, g0rd1 commented on core-tests/build.gradle.kts
> +    jvmToolchain(17)
Насколько понимаю нужно на 21 поменять или убрать эту строчку

2025-04-02 06:45 UTC, g0rd1 commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/log/Logger.kt
> +    fun error(tag: String, message: String, errorGroupId: String)
Предлагаю сделать errorGroupId необязательным аргументом с дефолтным значением null. Думаю не всем пользователям библиотеки нужна группа ошибок

2025-04-02 06:45 UTC, g0rd1 commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/log/Logger.kt
> +interface Logger {
Предлагаю интерфейс переписать во так:
```
fun interface Logger {
    fun log(tag: String, message: String)
    fun error(tag: String, message: String, errorGroupId: String? = null) = log(tag, message)
}
```

Тогда будет возможность пользователю библиотеки инициализировать логгер в одну строку:
```
open class LogParams<STATE : State, ACTION : Action<STATE>>(
    val loggerMode: LoggerMode,
    val tag: String? = null,
    val logger: Logger = Logger { _, message -> println("$tag: $message") },
    val logFormatters: LogFormatters<STATE, ACTION> = DefaultVerboseLogFormatters(),
)
```

2025-04-02 06:45 UTC, g0rd1 commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/Action.kt
>      private var transitions: List<Transition<out STATE, out STATE>>? = null
Раз мы делаем изменения ломающие обратную совместимость, то предлагаю избавится от установки переходов в `Action` (и поля `transitions`), а просто напрямую передавать их в метод `run`

2025-04-02 06:57 UTC, VasilyRylov commented on core-tests/build.gradle.kts
> +    jvmToolchain(17)
Эта строчка добавлена специально с целью компиляции java class 17 версии, иначе библиотеку VisualFSM можно будет использовать только на 21 таргете

2025-04-02 07:03 UTC, VasilyRylov commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/log/Logger.kt
> +    fun error(tag: String, message: String, errorGroupId: String)
Согласен, сделал необязательным аргументом

2025-04-02 07:29 UTC, VasilyRylov commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/log/Logger.kt
> +interface Logger {
Считаю что лучше явно описывать класс для логгера, отдельно от LogParams и не иметь логгирования ошибок по умолчанию, это подскажет пользователю что на логгирование ошибок он может сделать на свое усмотрение

2025-04-02 07:43 UTC, VasilyRylov commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/log/Logger.kt
> +    fun error(tag: String, message: String, errorGroupId: String)
Метод вызывается внутри библиотеки и errorGroupId всегда не null

2025-04-03 06:47 UTC, VasilyRylov commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/Action.kt
>      private var transitions: List<Transition<out STATE, out STATE>>? = null
Удалил устаревшие конструкции в Action

2025-04-03 12:09 UTC, g0rd1 approved these changes, later dismissed

2025-04-04 06:04 UTC, g0rd1 approved these changes

2025-04-04 06:07 UTC, merged