Added code generation to remove boilerplate code in Action implementations
Kontur-Mobile/VisualFSM pull request #5
Opened 2022-06-21 18:58 UTC by g0rd1

2022-06-27 06:00 UTC, VasilyRylov requested changes

2022-06-27 06:00 UTC, VasilyRylov commented on README.md
> +### Android App Setup
Android App Setup лучше сделать первым

2022-06-27 06:00 UTC, VasilyRylov commented on build.gradle
> +        coroutinesVersion = '1.6.2'
coroutinesVersion = '1.6.3', в 1.6.2 есть баг из-за которого не будет работать билд артефактов

2022-06-27 06:00 UTC, VasilyRylov commented on docs/README-RU.md
> +// Добавляем сгенерированный код в каталоги исходного кода
Нужно добавить имя файла build.gradle, и отдельно вариант для kts

2022-06-27 06:00 UTC, VasilyRylov commented on docs/README-RU.md
> +Как аннотировать классы и взаимодейтвовать с сгенерированным кодом смотри в [примере ниже](#AuthFeature.kt).
лучше не классы во множественном числе, а как аннотировать Feature класс

2022-06-27 06:00 UTC, VasilyRylov commented on docs/README-RU.md
> +`TransactionFactory` возвращает список `Transition` для экземпляра `Action`. Не рекомендуется создавать
Можно убрать "не рекомендуется" а прямо написать - используйте TransactionFactoryProvider в Android и сгенерированный класс "как формируется имя класса" в iOS

2022-06-27 06:00 UTC, VasilyRylov commented on visualfsm-compiler/src/main/kotlin/annotation_processor/AnnotationProcessor.kt
> +            .getSymbolsWithAnnotation(UsesGeneratedTransactionFactory::class.qualifiedName!!)
Предлагаю сократить, длинное имя тяжело воспринимается, например UsesGeneratedTransitionFactory -> GeneratedTransitionFactory -> GeneratedTransitions и обрати внимание в других местах что не путается Transition и Transaction

2022-06-27 06:00 UTC, VasilyRylov commented on visualfsm-compiler/src/main/kotlin/annotation_processor/functions/KSClassDeclarationFunctions.kt
> +    private const val MAX_SUPER_CLASS_SEARCH_NESTING_LEVEL = 5
А почему ограничение в 5?

2022-06-27 06:00 UTC, VasilyRylov commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/Feature.kt
> +    message = "Deprecated because it not support code generation. Using code generation is the recommended approach. Please see the readme file (https://github.com/Kontur-Mobile/VisualFSM#readme) for
Тут нужно написать чуть длиннее, в начале достаточную информацию - используйте аннотацию такую то и добавьте sourceSets в билд скрипт, а дальше ссылка на подробности

2022-06-27 06:00 UTC, VasilyRylov commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/Transition.kt
> +    lateinit var fromState: KClass<FROM>
Вместо lateinit предлагаю использовать nullable и при обращении если null кидать понятное IllegalState - используйте кодогенерацию

2022-06-27 06:00 UTC, VasilyRylov commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/UsesGeneratedTransactionFactory.kt
> +annotation class UsesGeneratedTransactionFactory
предлагаю GeneratedTransitions

2022-06-27 06:00 UTC, VasilyRylov commented on visualfsm-tools/src/main/kotlin/ru/kontur/mobile/visualfsm/tools/GeneratedTransactionFactoryProvider.kt
> +class GeneratedTransactionFactoryProvider {
Можно подумать над вынесением в отдельный модуль - для разделения зависимых от java reflect инструментов и независимых

2022-06-27 06:00 UTC, VasilyRylov commented on visualfsm-compiler/src/main/kotlin/annotation_processor/functions/KSClassDeclarationFunctions.kt
> +    fun KSClassDeclaration.getAllNestedSealedSubclasses(): Sequence<KSClassDeclaration> {
почему не internal?

2022-07-03 12:40 UTC, HerbalGreenTea commented on docs/ru/README-RU.md
> +набор состояний, которые выстраиваются в направленный граф.
Вроде обычно говорят "ориентированный граф", хотя так тоже вроде понятно, но написал на всякий

2022-07-03 12:48 UTC, HerbalGreenTea commented on visualfsm-tools/src/main/kotlin/ru/kontur/mobile/visualfsm/tools/GeneratedTransitionFactoryProvider.kt
> +        val implName = "Generated${featureClass.simpleName!!}TransitionFactory"
Возможно лучше как то явно обработать null чтобы не писать !!

2022-07-03 13:36 UTC, g0rd1 commented on docs/ru/README-RU.md
> +набор состояний, которые выстраиваются в направленный граф.
Я бы заменил. @VasilyRylov что думаешь?

2022-07-03 13:41 UTC, g0rd1 commented on visualfsm-tools/src/main/kotlin/ru/kontur/mobile/visualfsm/tools/GeneratedTransitionFactoryProvider.kt
> +        val implName = "Generated${featureClass.simpleName!!}TransitionFactory"
Да мне кажется незачем. Тут simpleName точно должно быть. Потому что-то если что-то не то помечено аннотацией GenerateTransitionFactory, то будет ошибка либо на этапе компиляции, либо при работе ksp.

2022-07-03 13:43 UTC, g0rd1 commented on visualfsm-tools/src/main/kotlin/ru/kontur/mobile/visualfsm/tools/GeneratedTransitionFactoryProvider.kt
> +        val implName = "Generated${featureClass.simpleName!!}TransitionFactory"
+ к этому метод "provideTransitionFactory" не получится вызвать не из наследника Feature. Так что защита надёжная.

2022-07-09 10:19 UTC, VasilyRylov commented on docs/ru/README-RU.md
> +набор состояний, которые выстраиваются в направленный граф.
Думаю можно заменить на ориентированный граф

2022-07-09 11:21 UTC, VasilyRylov requested changes

2022-07-09 11:21 UTC, VasilyRylov commented on docs/ru/Quickstart-RU.md
> +## Как подключить основные классы
Подключение зависимостей

2022-07-09 11:21 UTC, VasilyRylov commented on docs/ru/Quickstart-RU.md
> +# Первичная настройка
В самом верху блок ENG | RUS по аналогии с readme, и в русской и в английской версии

2022-07-09 11:21 UTC, VasilyRylov commented on docs/ru/Quickstart-RU.md
> +* Получения сгенерированных классов
Метод получения фабрики переходов provideTransitionsFactory() для jvm проектов  (отдельным модулем и без testImplementation)

2022-07-09 11:21 UTC, VasilyRylov commented on docs/ru/Quickstart-RU.md
> +#### _Для Котлин приложения_
Kotlin

2022-07-09 11:21 UTC, VasilyRylov commented on docs/ru/Quickstart-RU.md
> +##### В gradle файле модуля, в котором будут использованы аннотации
build.gradle

2022-07-09 11:21 UTC, VasilyRylov commented on docs/ru/Quickstart-RU.md
> +    id "com.google.devtools.ksp" version "1.6.21-1.0.6"
лучше не указывать конкретную версию а общим словом (kspVersion)

2022-07-09 11:21 UTC, VasilyRylov commented on docs/ru/Quickstart-RU.md
> +    implementation "ru.kontur.mobile.visualfsm:visualfsm-tools:1.1.0"
visualfsm-providers

2022-07-09 11:21 UTC, VasilyRylov commented on docs/ru/Quickstart-RU.md
> +    id("com.google.devtools.ksp") version "1.6.10-1.0.6"
лучше не указывать конкретную версию а общим словом (kspVersion)

2022-07-09 11:21 UTC, VasilyRylov commented on docs/ru/Quickstart-RU.md
> +##### В gradle файле модуля, в котором будут использованы аннотации
Тут и ниже использовать имена файлов

2022-07-09 11:21 UTC, VasilyRylov commented on docs/ru/Quickstart-RU.md
> +  <summary>Пример для не jvm проекта</summary>
Пример для KMM проекта

2022-07-09 11:21 UTC, VasilyRylov commented on docs/ru/Quickstart-RU.md
> +    2. Для не jvm проекта передавать экземпляр сгенерированного класса.
Для Kotlin Multiplatform проекта

2022-07-09 11:21 UTC, VasilyRylov commented on docs/ru/Quickstart-RU.md
> +    2. Для не jvm проекта передавать экземпляр сгенерированного класса.
Добавить комментарий что до первого запуска кодогенерации класс не будет виден в IDE

2022-07-09 11:21 UTC, VasilyRylov commented on docs/ru/Quickstart-RU.md
> +android {
android {
    ...  
    applicationVariants.all { variant ->
        variant.sourceSets.java.each {
            it.srcDirs += "build/generated/ksp/${variant.name}/kotlin"
        }
    }
}

2022-07-09 11:21 UTC, VasilyRylov commented on docs/ru/Quickstart-RU.md
> +android.applicationVariants.all {
Добавить ... выше и ниже с именами блоков, что-бы пользователю было понятнее где именно нужно написать

2022-07-09 11:21 UTC, VasilyRylov commented on docs/ru/Quickstart-RU.md
> +#### _Для Андроид приложения_
Android

2022-07-09 11:21 UTC, VasilyRylov commented on docs/ru/Quickstart-RU.md
> +</details>
Нужно добавить отдельную секцию для KMM проекта, так как конфигурация отличается:

```
plugins {
    kotlin("multiplatform")
    id("com.android.library")
    id("com.google.devtools.ksp") version (kspVersion)
}
...
    sourceSets {
        val commonMain by getting {
            dependencies { 
                ...
                implementation("ru.kontur.mobile.visualfsm:visualfsm-core:1.1.0")
                ...
                kotlin.srcDir("${buildDir.absolutePath}/generated/ksp/")
            }
        }
...
}
...
dependencies {
    add("kspAndroid", "ru.kontur.mobile.visualfsm:visualfsm-compiler:1.1.0")
}
...
android {
...
```

2022-07-09 11:21 UTC, VasilyRylov commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/Action.kt
> +                "See the readme file for more information on set up code generation (https://github.com/Kontur-Mobile/VisualFSM/blob/main/docs/eng/Quickstart-ENG.md).",
See the quickstart file for more information

2022-07-09 11:21 UTC, VasilyRylov commented on visualfsm-core/src/commonMain/kotlin/ru/kontur/mobile/visualfsm/TransitionFactory.kt
> +interface TransitionFactory<STATE : State, ACTION : Action<STATE>> {
Мне кажется имя TransitionsFactory больше подходит так как возвращаем list

2022-07-09 11:21 UTC, VasilyRylov commented on visualfsm-compiler/src/main/kotlin/annotation_processor/TransitionFactoryFileSpecFactory.kt
> +                    error("Action must not override getTransitions function. The \"${actionSealedSubclass.toClassName().canonicalName}\" does not meet this requirement.")
Возможно если выводить не полное имя класса, а путь до класса, используя ./../../ - он станет кликабельным для удобства навигации

2022-07-09 11:21 UTC, VasilyRylov commented on visualfsm-compiler/src/main/kotlin/annotation_processor/TransitionFactoryFileSpecFactory.kt
> +        createFunctionCodeBuilder.append("····else·->·error(\"All·sealed·subclasses·of·${baseActionClassDeclaration.toClassName().canonicalName}·must·be·handled·in·when\")\n")
IDE предупреждает о лишнем else после генерации фабрики

2022-07-14 14:23 UTC, VasilyRylov approved these changes

2022-07-14 14:24 UTC, merged